// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhupmimpslczikzdtcxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZodXBtaW1wc2xjemlremR0Y3hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2ODY1MDAsImV4cCI6MjA1MjI2MjUwMH0.9RJ8rw2CHbDKa49gf0v_K9AnyyHg55QiBDOEiZfIcM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);